require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReplanningEndorsementsController do

  # This should return the minimal set of attributes required to create a valid
  # ReplanningEndorsement. As you add validations to ReplanningEndorsement, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "developed_by_general_projector" => "false" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReplanningEndorsementsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all replanning_endorsements as @replanning_endorsements" do
      replanning_endorsement = ReplanningEndorsement.create! valid_attributes
      get :index, {}, valid_session
      assigns(:replanning_endorsements).should eq([replanning_endorsement])
    end
  end

  describe "GET show" do
    it "assigns the requested replanning_endorsement as @replanning_endorsement" do
      replanning_endorsement = ReplanningEndorsement.create! valid_attributes
      get :show, {:id => replanning_endorsement.to_param}, valid_session
      assigns(:replanning_endorsement).should eq(replanning_endorsement)
    end
  end

  describe "GET new" do
    it "assigns a new replanning_endorsement as @replanning_endorsement" do
      get :new, {}, valid_session
      assigns(:replanning_endorsement).should be_a_new(ReplanningEndorsement)
    end
  end

  describe "GET edit" do
    it "assigns the requested replanning_endorsement as @replanning_endorsement" do
      replanning_endorsement = ReplanningEndorsement.create! valid_attributes
      get :edit, {:id => replanning_endorsement.to_param}, valid_session
      assigns(:replanning_endorsement).should eq(replanning_endorsement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ReplanningEndorsement" do
        expect {
          post :create, {:replanning_endorsement => valid_attributes}, valid_session
        }.to change(ReplanningEndorsement, :count).by(1)
      end

      it "assigns a newly created replanning_endorsement as @replanning_endorsement" do
        post :create, {:replanning_endorsement => valid_attributes}, valid_session
        assigns(:replanning_endorsement).should be_a(ReplanningEndorsement)
        assigns(:replanning_endorsement).should be_persisted
      end

      it "redirects to the created replanning_endorsement" do
        post :create, {:replanning_endorsement => valid_attributes}, valid_session
        response.should redirect_to(ReplanningEndorsement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved replanning_endorsement as @replanning_endorsement" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReplanningEndorsement.any_instance.stub(:save).and_return(false)
        post :create, {:replanning_endorsement => { "developed_by_general_projector" => "invalid value" }}, valid_session
        assigns(:replanning_endorsement).should be_a_new(ReplanningEndorsement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReplanningEndorsement.any_instance.stub(:save).and_return(false)
        post :create, {:replanning_endorsement => { "developed_by_general_projector" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested replanning_endorsement" do
        replanning_endorsement = ReplanningEndorsement.create! valid_attributes
        # Assuming there are no other replanning_endorsements in the database, this
        # specifies that the ReplanningEndorsement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ReplanningEndorsement.any_instance.should_receive(:update_attributes).with({ "developed_by_general_projector" => "false" })
        put :update, {:id => replanning_endorsement.to_param, :replanning_endorsement => { "developed_by_general_projector" => "false" }}, valid_session
      end

      it "assigns the requested replanning_endorsement as @replanning_endorsement" do
        replanning_endorsement = ReplanningEndorsement.create! valid_attributes
        put :update, {:id => replanning_endorsement.to_param, :replanning_endorsement => valid_attributes}, valid_session
        assigns(:replanning_endorsement).should eq(replanning_endorsement)
      end

      it "redirects to the replanning_endorsement" do
        replanning_endorsement = ReplanningEndorsement.create! valid_attributes
        put :update, {:id => replanning_endorsement.to_param, :replanning_endorsement => valid_attributes}, valid_session
        response.should redirect_to(replanning_endorsement)
      end
    end

    describe "with invalid params" do
      it "assigns the replanning_endorsement as @replanning_endorsement" do
        replanning_endorsement = ReplanningEndorsement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReplanningEndorsement.any_instance.stub(:save).and_return(false)
        put :update, {:id => replanning_endorsement.to_param, :replanning_endorsement => { "developed_by_general_projector" => "invalid value" }}, valid_session
        assigns(:replanning_endorsement).should eq(replanning_endorsement)
      end

      it "re-renders the 'edit' template" do
        replanning_endorsement = ReplanningEndorsement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReplanningEndorsement.any_instance.stub(:save).and_return(false)
        put :update, {:id => replanning_endorsement.to_param, :replanning_endorsement => { "developed_by_general_projector" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested replanning_endorsement" do
      replanning_endorsement = ReplanningEndorsement.create! valid_attributes
      expect {
        delete :destroy, {:id => replanning_endorsement.to_param}, valid_session
      }.to change(ReplanningEndorsement, :count).by(-1)
    end

    it "redirects to the replanning_endorsements list" do
      replanning_endorsement = ReplanningEndorsement.create! valid_attributes
      delete :destroy, {:id => replanning_endorsement.to_param}, valid_session
      response.should redirect_to(replanning_endorsements_url)
    end
  end

end
